### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by HartzFrequency** [BuildersChain/Support#28]
### Name

Harsh Shrivastava

### Discord Username (if applicable)

Hartz#3666

**Comment by kartikver15gr8** [comment]
@

**Comment by kartikver15gr8** [comment]
@HartzFrequency 
Welcome to the community🎉🎉
Each contribution matters, lets learn together and skyrocket our learnings!

**Comment by HartzFrequency** [comment]
Thank you, Sir

**Comment by kartikver15gr8** [comment]
My Pleasure!
Make sure to make your community visibility ```public```
